# Generated by Django 6.0.6 on 2026-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_room_members_alter_room_state_alter_room_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.CharField(blank=True, null=True),
        ),
    ]
