# Generated by Django 6.0.6 on 2026-06-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
    ]
