# Generated by Django 6.0.6 on 2026-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
