# Generated by Django 6.0.6 on 2026-07-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_room_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
        migrations.RemoveField(
            model_name='room',
            name='time',
        ),
    ]
