# Generated by Django 6.0.6 on 2026-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_room_state_remove_room_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeDB',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
                ('link', models.CharField(null=True)),
            ],
        ),
    ]
